apiVersion: v1
kind: Service
metadata:
  name: mongodemo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    io.kompose.service: mongodemo
status:
  loadBalancer: {}
