apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodemo
  name: mongodemo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: mongodemo
    spec:
      containers:
      - image: mongo:latest
        name: mongodemo
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
