apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: navajo-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "navajo-static-ip"
spec:
  tls:
  - hosts:
    - kube.sendrato.com
  - secretName: sendratocrt
  backend:
    serviceName: navajo
    servicePort: 8182
